//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfessorPerformanceEvaluation.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProfessorPerformanceEvaluation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string ACCEPT_BUTTON {
            get {
                return ResourceManager.GetString("ACCEPT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar experiencia educativa a profesor.
        /// </summary>
        public static string ASSIGN_EDUCATIONAL_EXPERIENCE_TO_PROFESSOR_BUTTON {
            get {
                return ResourceManager.GetString("ASSIGN_EDUCATIONAL_EXPERIENCE_TO_PROFESSOR_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://localhost:3000/api/.
        /// </summary>
        public static string BASE_URL {
            get {
                return ResourceManager.GetString("BASE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string CANCEL_BUTTON {
            get {
                return ResourceManager.GetString("CANCEL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, compruebe la información ingresada e inténtelo nuevamente..
        /// </summary>
        public static string CHECK_ENTERED_INFORMATION_LABEL {
            get {
                return ResourceManager.GetString("CHECK_ENTERED_INFORMATION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información se eliminó correctamente del sistema..
        /// </summary>
        public static string DELETED_INFORMATION_LABEL {
            get {
                return ResourceManager.GetString("DELETED_INFORMATION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información ingresada corresponde a una experiencia educativa que ya se encuentra registrada en el sistema..
        /// </summary>
        public static string EDUCATIONAL_EXPERIENCE_ALREADY_REGISTERED_LABEL {
            get {
                return ResourceManager.GetString("EDUCATIONAL_EXPERIENCE_ALREADY_REGISTERED_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Experiencia educativa:.
        /// </summary>
        public static string EDUCATIONAL_EXPERIENCE_LABEL {
            get {
                return ResourceManager.GetString("EDUCATIONAL_EXPERIENCE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración del programa educativo.
        /// </summary>
        public static string EDUCATIONAL_PROGRAM_ADMINISTRATION_BUTTON {
            get {
                return ResourceManager.GetString("EDUCATIONAL_PROGRAM_ADMINISTRATION_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración del programa educativo..
        /// </summary>
        public static string EDUCATIONAL_PROGRAM_ADMINISTRATION_LABEL {
            get {
                return ResourceManager.GetString("EDUCATIONAL_PROGRAM_ADMINISTRATION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información ingresada corresponde a un programa educativo que ya se encuentra registrado en el sistema..
        /// </summary>
        public static string EDUCATIONAL_PROGRAM_ALREADY_REGISTERED_LABEL {
            get {
                return ResourceManager.GetString("EDUCATIONAL_PROGRAM_ALREADY_REGISTERED_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programa educativo:.
        /// </summary>
        public static string EDUCATIONAL_PROGRAM_LABEL {
            get {
                return ResourceManager.GetString("EDUCATIONAL_PROGRAM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del programa educativo.
        /// </summary>
        public static string EDUCATIONAL_PROGRAM_NAME_LABEL {
            get {
                return ResourceManager.GetString("EDUCATIONAL_PROGRAM_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Title of the document&lt;/title&gt;
        ///    &lt;style&gt;
        ///        table.border {
        ///            border-collapse: collapse;
        ///        }
        ///
        ///            table.border th {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///
        ///            table.border td {
        ///                padding: 5px;
        ///                border: 1px solid black;
        ///            }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table style=&quot;width:100%&quot;&gt;
        ///        [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EducationalExperienceReportFormat {
            get {
                return ResourceManager.GetString("EducationalExperienceReportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede dejar ningún campo vacío..
        /// </summary>
        public static string EMPTY_FIELDS_LABEL {
            get {
                return ResourceManager.GetString("EMPTY_FIELDS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sesión ha expirado..
        /// </summary>
        public static string EXPIRED_SESSION_LABEL {
            get {
                return ResourceManager.GetString("EXPIRED_SESSION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El programa educativo solo puede pertenecer a una facultad..
        /// </summary>
        public static string FACULTY_BY_EDUCATIONAL_PROGRAM_LABEL {
            get {
                return ResourceManager.GetString("FACULTY_BY_EDUCATIONAL_PROGRAM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la facultad.
        /// </summary>
        public static string FACULTY_NAME_LABEL {
            get {
                return ResourceManager.GetString("FACULTY_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar reporte de actividad por estudiante.
        /// </summary>
        public static string GENERATE_ACTIVITY_REPORT_BY_STUDENT_BUTTON {
            get {
                return ResourceManager.GetString("GENERATE_ACTIVITY_REPORT_BY_STUDENT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar reporte de desempeño docente por experiencia educativa.
        /// </summary>
        public static string GENERATE_PROFESSOR_PERFORMANCE_REPORT_BY_EDUCATIONAL_EXPERIENCE_BUTTON {
            get {
                return ResourceManager.GetString("GENERATE_PROFESSOR_PERFORMANCE_REPORT_BY_EDUCATIONAL_EXPERIENCE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar reporte de desempeño docente por profesor.
        /// </summary>
        public static string GENERATE_PROFESSOR_PERFORMANCE_REPORT_BY_PROFESSOR_BUTTON {
            get {
                return ResourceManager.GetString("GENERATE_PROFESSOR_PERFORMANCE_REPORT_BY_PROFESSOR_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos ingresados son inválidos..
        /// </summary>
        public static string INVALID_DATA_LABEL {
            get {
                return ResourceManager.GetString("INVALID_DATA_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar experiencia educativa.
        /// </summary>
        public static string LOG_EDUCATIONAL_EXPERIENCE_BUTTON {
            get {
                return ResourceManager.GetString("LOG_EDUCATIONAL_EXPERIENCE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la información de la experiencia educativa y dé clic en el botón de &quot;Aceptar&quot;..
        /// </summary>
        public static string LOG_EDUCATIONAL_EXPERIENCE_INSTRUCTION_LABEL {
            get {
                return ResourceManager.GetString("LOG_EDUCATIONAL_EXPERIENCE_INSTRUCTION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar experiencia educativa..
        /// </summary>
        public static string LOG_EDUCATIONAL_EXPERIENCE_LABEL {
            get {
                return ResourceManager.GetString("LOG_EDUCATIONAL_EXPERIENCE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar programa educativo.
        /// </summary>
        public static string LOG_EDUCATIONAL_PROGRAM_BUTTON {
            get {
                return ResourceManager.GetString("LOG_EDUCATIONAL_PROGRAM_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la información del programa educativo y dé clic en el botón de &quot;Aceptar&quot;..
        /// </summary>
        public static string LOG_EDUCATIONAL_PROGRAM_INSTRUCTION_LABEL {
            get {
                return ResourceManager.GetString("LOG_EDUCATIONAL_PROGRAM_INSTRUCTION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string LOG_OUT_BUTTON {
            get {
                return ResourceManager.GetString("LOG_OUT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar profesor.
        /// </summary>
        public static string LOG_PROFESSOR_BUTTON {
            get {
                return ResourceManager.GetString("LOG_PROFESSOR_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string LOGIN_BUTTON {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión..
        /// </summary>
        public static string LOGIN_LABEL {
            get {
                return ResourceManager.GetString("LOGIN_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú principal..
        /// </summary>
        public static string MAIN_MENU_LABEL {
            get {
                return ResourceManager.GetString("MAIN_MENU_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar facultades.
        /// </summary>
        public static string MANAGE_FACULTIES_BUTTON {
            get {
                return ResourceManager.GetString("MANAGE_FACULTIES_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información se modificó correctamente en el sistema..
        /// </summary>
        public static string MODIFIED_INFORMATION_LABEL {
            get {
                return ResourceManager.GetString("MODIFIED_INFORMATION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar experiencia educativa.
        /// </summary>
        public static string MODIFY_EDUCATIONAL_EXPERIENCE_BUTTON {
            get {
                return ResourceManager.GetString("MODIFY_EDUCATIONAL_EXPERIENCE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar experiencia educativa..
        /// </summary>
        public static string MODIFY_EDUCATIONAL_EXPERIENCE_LABEL {
            get {
                return ResourceManager.GetString("MODIFY_EDUCATIONAL_EXPERIENCE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar programa educativo.
        /// </summary>
        public static string MODIFY_EDUCATIONAL_PROGRAM_BUTTON {
            get {
                return ResourceManager.GetString("MODIFY_EDUCATIONAL_PROGRAM_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar programa educativo..
        /// </summary>
        public static string MODIFY_EDUCATIONAL_PROGRAM_LABEL {
            get {
                return ResourceManager.GetString("MODIFY_EDUCATIONAL_PROGRAM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar profesor.
        /// </summary>
        public static string MODIFY_PROFESSOR_BUTTON {
            get {
                return ResourceManager.GetString("MODIFY_PROFESSOR_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        public static string NAME_LABEL {
            get {
                return ResourceManager.GetString("NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación de contraseña:.
        /// </summary>
        public static string PASSWORD_CONFIRMATION_LABEL {
            get {
                return ResourceManager.GetString("PASSWORD_CONFIRMATION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        public static string PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de evaluaciones al desempeño docente.
        /// </summary>
        public static string PROFESSOR_PERFORMANCE_EVALUATIONS_MANAGEMENT_BUTTON {
            get {
                return ResourceManager.GetString("PROFESSOR_PERFORMANCE_EVALUATIONS_MANAGEMENT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información se registró correctamente en el sistema..
        /// </summary>
        public static string REGISTERED_INFORMATION_LABEL {
            get {
                return ResourceManager.GetString("REGISTERED_INFORMATION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string RETURN_BUTTON {
            get {
                return ResourceManager.GetString("RETURN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servicio no está disponible..
        /// </summary>
        public static string SERVICE_NOT_AVAILABLE_LABEL {
            get {
                return ResourceManager.GetString("SERVICE_NOT_AVAILABLE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string SIGN_UP_BUTTON {
            get {
                return ResourceManager.GetString("SIGN_UP_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta..
        /// </summary>
        public static string SIGN_UP_LABEL {
            get {
                return ResourceManager.GetString("SIGN_UP_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generación de reportes específicos.
        /// </summary>
        public static string SPECIFIC_REPORT_GENERATION_BUTTON {
            get {
                return ResourceManager.GetString("SPECIFIC_REPORT_GENERATION_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generación de reportes específicos..
        /// </summary>
        public static string SPECIFIC_REPORT_GENERATION_LABEL {
            get {
                return ResourceManager.GetString("SPECIFIC_REPORT_GENERATION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de estudiantes.
        /// </summary>
        public static string STUDENT_MANAGEMENT_BUTTON {
            get {
                return ResourceManager.GetString("STUDENT_MANAGEMENT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, inténtelo más tarde..
        /// </summary>
        public static string TRY_AGAIN_LATER_LABEL {
            get {
                return ResourceManager.GetString("TRY_AGAIN_LATER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información ingresada corresponde a un usuario que ya se encuentra registrado en el sistema..
        /// </summary>
        public static string USER_ALREADY_REGISTERED_LABEL {
            get {
                return ResourceManager.GetString("USER_ALREADY_REGISTERED_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario:.
        /// </summary>
        public static string USERNAME_LABEL {
            get {
                return ResourceManager.GetString("USERNAME_LABEL", resourceCulture);
            }
        }
    }
}
